{
  "swagger" : "2.0",
  "info" : {
    "version" : "0.9.6",
    "title" : "OrderSolution HTTP API"
  },
  "host" : "10.0.0.136:12346",
  "schemes" : [ "http" ],
  "consumes" : [ "application/json-patch+json", "application/json", "text/json", "application/*+json" ],
  "paths" : {
    "/Documentation/Index" : { },
    "/api/v2/data/CancellationReasons" : {
      "get" : {
        "tags" : [ "data" ],
        "operationId" : "CancellationReasons_Get",
        "produces" : [ "application/json" ],
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "",
            "schema" : {
              "type" : "array",
              "items" : {
                "$ref" : "#/definitions/CancellationReason"
              }
            },
            "x-nullable" : true
          }
        }
      }
    },
    "/api/v2/HostStatus" : {
      "get" : {
        "tags" : [ "host" ],
        "summary" : "Get the status of the host / POS. This will be regularly called by clients to detect status changes (like host / POS restarts)",
        "operationId" : "HostStatus_Get",
        "produces" : [ "application/json" ],
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "",
            "schema" : {
              "$ref" : "#/definitions/PosStatus"
            },
            "x-nullable" : true
          }
        }
      }
    },
    "/api/v2/data/OsConfiguration" : {
      "get" : {
        "tags" : [ "data" ],
        "operationId" : "OsConfiguration_Get",
        "produces" : [ "application/json" ],
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "",
            "schema" : {
              "$ref" : "#/definitions/OsConfiguration"
            },
            "x-nullable" : true
          }
        }
      }
    },
    "/api/v2/data/PaymentMedia" : {
      "get" : {
        "tags" : [ "data" ],
        "operationId" : "PaymentMedia_Get",
        "produces" : [ "application/json" ],
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "",
            "schema" : {
              "type" : "array",
              "items" : {
                "$ref" : "#/definitions/PaymentMedium"
              }
            },
            "x-nullable" : true
          }
        }
      }
    },
    "/api/v2/data/Printers" : {
      "get" : {
        "tags" : [ "data" ],
        "operationId" : "Printers_Get",
        "produces" : [ "application/json" ],
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "",
            "schema" : {
              "type" : "array",
              "items" : {
                "$ref" : "#/definitions/Printer"
              }
            },
            "x-nullable" : true
          }
        }
      }
    },
    "/api/v2/data/Articles" : {
      "get" : {
        "tags" : [ "data" ],
        "operationId" : "Articles_Get",
        "produces" : [ "application/json" ],
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "",
            "schema" : {
              "type" : "array",
              "items" : {
                "$ref" : "#/definitions/Article"
              }
            },
            "x-nullable" : true
          }
        }
      }
    },
    "/api/v2/data/Categories" : {
      "get" : {
        "tags" : [ "data" ],
        "operationId" : "Categories_Get",
        "produces" : [ "application/json" ],
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "",
            "schema" : {
              "type" : "array",
              "items" : {
                "$ref" : "#/definitions/Category"
              }
            },
            "x-nullable" : true
          }
        }
      }
    },
    "/api/v2/images/fax/{id}" : {
      "get" : {
        "tags" : [ "images/fax" ],
        "operationId" : "FaxImage_Get",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "type" : "string",
          "x-nullable" : true
        } ],
        "responses" : {
          "200" : {
            "description" : "",
            "schema" : {
              "type" : "file"
            },
            "x-nullable" : true
          }
        }
      },
      "put" : {
        "tags" : [ "images/fax" ],
        "summary" : "Replace an existing fax image on the server.\nNOTE: The data will be read from the body as raw binary bytes.",
        "operationId" : "FaxImage_Put",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "The ID of the fax image to overwrite.",
          "required" : true,
          "type" : "string",
          "x-nullable" : true
        } ],
        "responses" : {
          "204" : {
            "description" : ""
          }
        }
      }
    },
    "/api/v2/images/fax" : {
      "post" : {
        "tags" : [ "images/fax" ],
        "summary" : "Store a new fax image on the server.\nNOTE: The data will be read from the body as raw binary bytes.",
        "operationId" : "FaxImage_Post",
        "parameters" : [ {
          "name" : "subTableId",
          "in" : "query",
          "description" : "Context information about the sub table to which the fax image is planned to be sent for.\nWhen later reffering to the fax image id we will always do so in the context of that sub table.\nThis also means in case the sub table is not valid anymore (e.g. closed via payment) the OrderSolution also does not have a need for\nthat image anymore which means the image can safely be deleted (from the OrderSolution perspective).",
          "required" : false,
          "type" : "string",
          "x-nullable" : true
        } ],
        "responses" : {
          "201" : {
            "description" : "On success it will return the location of the newly stored image in location header."
          },
          "400" : {
            "description" : "",
            "schema" : {
              "$ref" : "#/definitions/OsError"
            },
            "x-nullable" : true
          },
          "403" : {
            "description" : "",
            "schema" : {
              "$ref" : "#/definitions/OsError"
            },
            "x-nullable" : true
          }
        }
      }
    },
    "/api/v2/data/ModifierGroups" : {
      "get" : {
        "tags" : [ "data" ],
        "operationId" : "ModifierGroups_Get",
        "produces" : [ "application/json" ],
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "",
            "schema" : {
              "type" : "array",
              "items" : {
                "$ref" : "#/definitions/ModifierGroup"
              }
            },
            "x-nullable" : true
          }
        }
      }
    },
    "/api/v2/data/OrderLines" : {
      "get" : {
        "tags" : [ "runtime data" ],
        "summary" : "Get the order lines possibly filtered by the sub table id.\nNOTE: Only commited order lines (where actions/tables/FinalizeOrder was called) will be returned by this call.",
        "operationId" : "OrderLines_Get",
        "parameters" : [ {
          "name" : "subTableId",
          "in" : "query",
          "description" : "The sub table ID getting orderlines for.",
          "required" : false,
          "type" : "string",
          "x-nullable" : true
        }, {
          "name" : "status",
          "in" : "query",
          "description" : "If specified the status of the orderlines that are required.\n            If not provided all orderlines with status Ordered and Committed are returned",
          "required" : false,
          "type" : "string",
          "enum" : [ "unknown", "ordered", "committed", "paid" ],
          "x-schema" : {
            "$ref" : "#/definitions/OrderLineStatus"
          },
          "x-nullable" : true
        } ],
        "responses" : {
          "200" : {
            "description" : "Orderlines with their unpaid quantity/price",
            "schema" : {
              "type" : "array",
              "items" : {
                "$ref" : "#/definitions/OrderLine"
              }
            },
            "x-nullable" : true
          }
        }
      }
    },
    "/api/v2/data/ServiceAreas" : {
      "get" : {
        "tags" : [ "data" ],
        "operationId" : "ServiceAreas_Get",
        "produces" : [ "application/json" ],
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "",
            "schema" : {
              "type" : "array",
              "items" : {
                "$ref" : "#/definitions/ServiceArea"
              }
            },
            "x-nullable" : true
          }
        }
      }
    },
    "/api/v2/data/Tables" : {
      "get" : {
        "tags" : [ "runtime data" ],
        "summary" : "Get open tables for the service area.",
        "operationId" : "Tables_GetOpen",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "serviceAreaId",
          "in" : "query",
          "description" : "The service area id of the service area.",
          "required" : false,
          "type" : "string",
          "x-nullable" : true
        } ],
        "responses" : {
          "200" : {
            "description" : "open tables array",
            "schema" : {
              "type" : "array",
              "items" : {
                "$ref" : "#/definitions/TableResult"
              }
            },
            "x-nullable" : true
          }
        }
      }
    },
    "/api/v2/data/Users" : {
      "get" : {
        "tags" : [ "data" ],
        "operationId" : "Users_Get",
        "produces" : [ "application/json" ],
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "",
            "schema" : {
              "type" : "array",
              "items" : {
                "$ref" : "#/definitions/User"
              }
            },
            "x-nullable" : true
          }
        }
      }
    },
    "/api/v2/actions/Auth/Login" : {
      "post" : {
        "tags" : [ "actions" ],
        "summary" : "Execute a login transaciton. NOTE: Will set an \"AuthToken\" cookie needed in later authorized requests.",
        "operationId" : "Auth_Login",
        "consumes" : [ "application/json-patch+json", "application/json", "text/json", "application/*+json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "data",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/LoginUser"
          },
          "x-nullable" : false
        } ],
        "responses" : {
          "201" : {
            "description" : ""
          },
          "401" : {
            "description" : "",
            "schema" : {
              "$ref" : "#/definitions/OsError"
            },
            "x-nullable" : true
          }
        }
      }
    },
    "/api/v2/actions/Auth/Logout" : {
      "post" : {
        "tags" : [ "actions" ],
        "summary" : "Logout from the server.",
        "operationId" : "Auth_Logout",
        "parameters" : [ ],
        "responses" : {
          "204" : {
            "description" : ""
          }
        }
      }
    },
    "/api/v2/actions/Init/RegisterClient" : {
      "post" : {
        "tags" : [ "actions" ],
        "summary" : "Get initialization data for the client.\nClients will have to call transactions/login to execute meaningful transactions.",
        "operationId" : "Init_RegisterClient",
        "consumes" : [ "application/json-patch+json", "application/json", "text/json", "application/*+json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "clientData",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/ClientInfo"
          },
          "x-nullable" : false
        } ],
        "responses" : {
          "200" : {
            "description" : "",
            "schema" : {
              "$ref" : "#/definitions/POSInfo"
            },
            "x-nullable" : true
          },
          "400" : {
            "description" : "",
            "schema" : {
              "$ref" : "#/definitions/OsError"
            },
            "x-nullable" : true
          },
          "412" : {
            "description" : "",
            "schema" : {
              "$ref" : "#/definitions/OsError"
            },
            "x-nullable" : true
          }
        }
      }
    },
    "/api/v2/actions/Init/RegisterGateway" : {
      "post" : {
        "tags" : [ "actions" ],
        "summary" : "Informs about a gateway (like OsServer) that is configured to work with this POS.\nA gateway is a system / server that clients use to communicate with the server.",
        "operationId" : "Init_RegisterGateway",
        "consumes" : [ "application/json-patch+json", "application/json", "text/json", "application/*+json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "gatewayInfo",
          "description" : "Information about the gateway.",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/GatewayInfo"
          },
          "x-nullable" : false
        } ],
        "responses" : {
          "204" : {
            "description" : "",
            "schema" : { },
            "x-nullable" : true
          }
        }
      }
    },
    "/api/v2/actions/OrderLines/Void/{orderLineId}" : {
      "post" : {
        "tags" : [ "actions/orderlines" ],
        "summary" : "Void an orderline or a given quantity of it.",
        "operationId" : "OrderLines_Void",
        "consumes" : [ "application/json-patch+json", "application/json", "text/json", "application/*+json" ],
        "parameters" : [ {
          "name" : "orderLineId",
          "in" : "path",
          "description" : "The order line id to void / to reduce the quantity of.",
          "required" : true,
          "type" : "string",
          "x-nullable" : true
        }, {
          "in" : "body",
          "name" : "data",
          "description" : "Details about the void operation to be executed on this orderline. \n            If null the whole orderline will be voided.",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/OrderLineVoid"
          },
          "x-nullable" : false
        } ],
        "responses" : {
          "200" : {
            "description" : "",
            "schema" : {
              "$ref" : "#/definitions/OrderLineVoidResult"
            },
            "x-nullable" : true
          },
          "204" : {
            "description" : ""
          }
        }
      }
    },
    "/api/v2/actions/OrderLines/Add/{subTableId}" : {
      "post" : {
        "tags" : [ "actions/orderlines" ],
        "summary" : "Add a new orderline to a sub table.\n(e.g. when the waiter orders an article on a table)",
        "operationId" : "OrderLines_Add",
        "consumes" : [ "application/json-patch+json", "application/json", "text/json", "application/*+json" ],
        "parameters" : [ {
          "name" : "subTableId",
          "in" : "path",
          "description" : "The ID of the subtable to add the order line to.\nNote: Orders are always part of a subtable and subtables are part of a table. This means at least 1 subtable exists for each table to allow ordering / adding orderlines.",
          "required" : true,
          "type" : "string",
          "x-nullable" : true
        }, {
          "in" : "body",
          "name" : "data",
          "description" : "The orderline to add.",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/OrderLineAdd"
          },
          "x-nullable" : false
        } ],
        "responses" : {
          "201" : {
            "description" : "",
            "schema" : {
              "$ref" : "#/definitions/OrderLineResult"
            },
            "x-nullable" : true
          }
        }
      }
    },
    "/api/v2/actions/OrderLines/ModifyUncommitted/{orderLineId}" : {
      "post" : {
        "tags" : [ "actions/orderlines" ],
        "summary" : "Modifies (= replaces) an uncommited orderline.\nIMPORTANT: Any existing modifiers of the orderline are replaced with the new modifiers. \nFor example if an orderline \"1x Coke with ice\" is modified to be \"1x Coke with Citron\" the ice is also gone\nso the operation works as a replacement and not as a patch of the existing data.",
        "operationId" : "OrderLines_ModifyUncommitted",
        "consumes" : [ "application/json-patch+json", "application/json", "text/json", "application/*+json" ],
        "parameters" : [ {
          "name" : "orderLineId",
          "in" : "path",
          "description" : "The orderline to be modified / replaced",
          "required" : true,
          "type" : "string",
          "x-nullable" : true
        }, {
          "in" : "body",
          "name" : "data",
          "description" : "The new data to be used for this order line (same as for the add request)",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/OrderLineModify"
          },
          "x-nullable" : false
        } ],
        "responses" : {
          "201" : {
            "description" : "OrderLineResult informing about the new ids / prices of the modified orderline.",
            "schema" : {
              "$ref" : "#/definitions/OrderLineResult"
            },
            "x-nullable" : true
          }
        }
      }
    },
    "/api/v2/actions/Pay/SubTables" : {
      "post" : {
        "tags" : [ "actions/pay" ],
        "summary" : "Pay sub full subtables. If the pay action is executed successfully the subtables will be fully paid and clsoed.",
        "operationId" : "Pay_SubTables",
        "consumes" : [ "application/json-patch+json", "application/json", "text/json", "application/*+json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "data",
          "description" : "Pay data describing which payments have to be executed for which subtables",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/PaySubTables"
          },
          "x-nullable" : false
        } ],
        "responses" : {
          "204" : {
            "description" : "OK in case the payment was successfull and the receipt is moved to the printer queue."
          }
        }
      }
    },
    "/api/v2/actions/Pay/OrderLines" : {
      "post" : {
        "tags" : [ "actions/pay" ],
        "summary" : "Pay individual orderlines. Typically used when the bill is splitted.",
        "operationId" : "Pay_OrderLines",
        "consumes" : [ "application/json-patch+json", "application/json", "text/json", "application/*+json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "data",
          "description" : "The orderlines to be paid + payment info.",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/PayOrderLines"
          },
          "x-nullable" : false
        } ],
        "responses" : {
          "204" : {
            "description" : ""
          }
        }
      }
    },
    "/api/v2/actions/SubTables/Create" : {
      "post" : {
        "tags" : [ "actions/subtables" ],
        "summary" : "Create a new subtable.",
        "operationId" : "SubTables_Create",
        "parameters" : [ {
          "name" : "tableId",
          "in" : "query",
          "description" : "The table this sub table is created for.",
          "required" : false,
          "type" : "string",
          "x-nullable" : true
        } ],
        "responses" : {
          "201" : {
            "description" : "",
            "schema" : {
              "$ref" : "#/definitions/SubTable"
            },
            "x-nullable" : true
          }
        }
      }
    },
    "/api/v2/actions/Tables/OpenByName/{name}" : {
      "post" : {
        "tags" : [ "actions/tables" ],
        "summary" : "Open table by name. If it does not exist it will be created.",
        "operationId" : "Tables_OpenByName",
        "parameters" : [ {
          "name" : "name",
          "in" : "path",
          "description" : "The Name of the table to be opened. Is unique in the service area defined.",
          "required" : true,
          "type" : "string",
          "x-nullable" : true
        }, {
          "name" : "serviceAreaId",
          "in" : "query",
          "description" : "The ID of the service area in which the table should be opened.",
          "required" : false,
          "type" : "string",
          "x-nullable" : true
        }, {
          "name" : "prePayment",
          "in" : "query",
          "description" : "If provided defines if the request is in preparation of a payment action.",
          "required" : false,
          "type" : "boolean",
          "default" : false,
          "x-nullable" : true
        } ],
        "responses" : {
          "200" : {
            "description" : "",
            "schema" : {
              "$ref" : "#/definitions/TableResult"
            },
            "x-nullable" : true
          },
          "201" : {
            "description" : "",
            "schema" : {
              "$ref" : "#/definitions/TableResult"
            },
            "x-nullable" : true
          }
        }
      }
    },
    "/api/v2/actions/Tables/FinalizeOrder/{tableId}" : {
      "post" : {
        "tags" : [ "actions/tables" ],
        "summary" : "Finalize the current order so that they the open orders are commited and the table is getting unlocked.",
        "operationId" : "Tables_FinalizeOrder",
        "parameters" : [ {
          "name" : "tableId",
          "in" : "path",
          "description" : "Table to commit orders for.",
          "required" : true,
          "type" : "string",
          "x-nullable" : true
        } ],
        "responses" : {
          "204" : {
            "description" : ""
          },
          "401" : {
            "description" : ""
          },
          "403" : {
            "description" : ""
          },
          "409" : {
            "description" : ""
          }
        }
      }
    },
    "/api/v2/actions/Tables/CancelOrder/{tableId}" : {
      "post" : {
        "tags" : [ "actions/tables" ],
        "summary" : "Cancles the current order procedure for the table. The table will be unlocked and all uncommited orders will be deleted.",
        "operationId" : "Tables_CancelOrder",
        "parameters" : [ {
          "name" : "tableId",
          "in" : "path",
          "description" : "The table to work on.",
          "required" : true,
          "type" : "string",
          "x-nullable" : true
        } ],
        "responses" : {
          "204" : {
            "description" : ""
          },
          "401" : {
            "description" : ""
          },
          "403" : {
            "description" : ""
          },
          "409" : {
            "description" : ""
          }
        }
      }
    }
  },
  "definitions" : {
    "CancellationReason" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        }
      },
      "example" : {
        "name" : "name",
        "id" : "id"
      }
    },
    "PosStatus" : {
      "type" : "object",
      "properties" : {
        "sessionId" : {
          "type" : "string",
          "description" : "Whenever the POS is restarted this session should change to allow the gateway to detect restarts."
        }
      },
      "example" : {
        "sessionId" : "sessionId"
      }
    },
    "OsConfiguration" : {
      "type" : "object",
      "properties" : {
        "global" : {
          "type" : "object",
          "description" : "Key = key of configuration\nValue = value of the configuration",
          "additionalProperties" : {
            "type" : "string"
          }
        }
      },
      "example" : {
        "global" : {
          "key" : "global"
        }
      }
    },
    "PaymentMedium" : {
      "type" : "object",
      "required" : [ "allowOverPayment" ],
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "allowOverPayment" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "Optional. 0 = when using this media the app will not allow to enter a higher payment amount as to be paid. 1 = over payment is allowed"
        }
      },
      "example" : {
        "name" : "name",
        "id" : "id",
        "allowOverPayment" : 0
      }
    },
    "Printer" : {
      "type" : "object",
      "properties" : {
        "name" : {
          "type" : "string",
          "description" : "The friendly name of the printer informing the employee about which printer it is\nor where the printer might be connected to (like if it is a belt printer it should be clear\nfrom the name to which handheld this belt printer is connected to)"
        },
        "path" : {
          "type" : "string",
          "description" : "The path of the printer used to define the printer to which a print job is sent"
        }
      },
      "example" : {
        "path" : "path",
        "name" : "name"
      }
    },
    "Article" : {
      "type" : "object",
      "required" : [ "mustEnterPrice" ],
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "receiptName" : {
          "type" : "string"
        },
        "plu" : {
          "type" : "string"
        },
        "mustEnterPrice" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "Defines if the Article force price entry when ordered.\n0 = not forced; 1 = price entry forced"
        },
        "forceShowModifiers" : {
          "type" : "boolean",
          "description" : "If set to true AND modifier groups are assigned it forces the modifier screen to be shown right after the article was selected for ordering. (replaces the .IsMandatory from previous versions)"
        },
        "modifierGroups" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/ArticleModifierGroup"
          }
        }
      },
      "example" : {
        "receiptName" : "receiptName",
        "name" : "name",
        "plu" : "plu",
        "forceShowModifiers" : true,
        "id" : "id",
        "modifierGroups" : [ {
          "modifierGroupId" : "modifierGroupId"
        }, {
          "modifierGroupId" : "modifierGroupId"
        } ],
        "mustEnterPrice" : 0
      }
    },
    "ArticleModifierGroup" : {
      "type" : "object",
      "properties" : {
        "modifierGroupId" : {
          "type" : "string"
        }
      },
      "example" : {
        "modifierGroupId" : "modifierGroupId"
      }
    },
    "Category" : {
      "type" : "object",
      "properties" : {
        "name" : {
          "type" : "string"
        },
        "content" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/CategoryContentEntry"
          }
        }
      },
      "example" : {
        "name" : "name",
        "content" : [ {
          "articleId" : "articleId"
        }, {
          "articleId" : "articleId"
        } ]
      }
    },
    "CategoryContentEntry" : {
      "type" : "object",
      "properties" : {
        "category" : {
          "$ref" : "#/definitions/Category"
        },
        "articleId" : {
          "type" : "string"
        }
      },
      "example" : {
        "articleId" : "articleId"
      }
    },
    "OsError" : {
      "type" : "object",
      "properties" : {
        "errorMsg" : {
          "type" : "string"
        }
      }
    },
    "ModifierGroup" : {
      "type" : "object",
      "required" : [ "type" ],
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "question" : {
          "type" : "string"
        },
        "type" : {
          "$ref" : "#/definitions/ModifierType"
        },
        "minChoices" : {
          "type" : "integer",
          "format" : "int32"
        },
        "maxChoices" : {
          "type" : "integer",
          "format" : "int32"
        },
        "choices" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/ModifierChoice"
          }
        }
      },
      "example" : {
        "question" : "question",
        "name" : "name",
        "maxChoices" : 6,
        "id" : "id",
        "type" : { },
        "choices" : [ {
          "receiptName" : "receiptName",
          "minAmount" : 5,
          "defaultAmount" : 1,
          "name" : "name",
          "id" : "id",
          "maxAmount" : 5
        }, {
          "receiptName" : "receiptName",
          "minAmount" : 5,
          "defaultAmount" : 1,
          "name" : "name",
          "id" : "id",
          "maxAmount" : 5
        } ],
        "minChoices" : 0
      }
    },
    "ModifierType" : {
      "type" : "string",
      "description" : "0 – pickOne - One option to select from ModifierGroupChoices.\n1 – pickMultiple - Select several options from ModifierGroupChoices.\n2 – pickNumeric - Select numeric choices from ModifierGroupChoices\n3 – textInput -  Asks for arbitary text input\n4 – faxInput - Asks for handwritten input",
      "enum" : [ "pickOne", "pickMultiple", "pickNumeric", "textInput", "faxInput" ],
      "x-enumNames" : [ "PickOne", "PickMultiple", "PickNumeric", "textInput", "faxInput" ],
      "x-enum-string" : true
    },
    "ModifierChoice" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "receiptName" : {
          "type" : "string"
        },
        "defaultAmount" : {
          "type" : "integer",
          "format" : "int32"
        },
        "minAmount" : {
          "type" : "integer",
          "format" : "int32"
        },
        "maxAmount" : {
          "type" : "integer",
          "format" : "int32"
        }
      },
      "example" : {
        "receiptName" : "receiptName",
        "minAmount" : 5,
        "defaultAmount" : 1,
        "name" : "name",
        "id" : "id",
        "maxAmount" : 5
      }
    },
    "OrderLine" : {
      "type" : "object",
      "required" : [ "quantity", "singlePrice", "status" ],
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "articleId" : {
          "type" : "string"
        },
        "quantity" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "The unpaid quantity of this orderline."
        },
        "singlePrice" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "The unpaid price of this orderline."
        },
        "status" : {
          "$ref" : "#/definitions/OrderLineStatus"
        },
        "modifiers" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/OrderLineModifier"
          }
        }
      },
      "example" : {
        "singlePrice" : 6,
        "quantity" : 0,
        "articleId" : "articleId",
        "id" : "id",
        "modifiers" : [ {
          "textInput" : "textInput",
          "faxInputID" : "faxInputID",
          "id" : "id",
          "choices" : [ {
            "amount" : 1,
            "choicePrice" : 5,
            "modifierChoiceId" : "modifierChoiceId"
          }, {
            "amount" : 1,
            "choicePrice" : 5,
            "modifierChoiceId" : "modifierChoiceId"
          } ],
          "modifierGroupId" : "modifierGroupId"
        }, {
          "textInput" : "textInput",
          "faxInputID" : "faxInputID",
          "id" : "id",
          "choices" : [ {
            "amount" : 1,
            "choicePrice" : 5,
            "modifierChoiceId" : "modifierChoiceId"
          }, {
            "amount" : 1,
            "choicePrice" : 5,
            "modifierChoiceId" : "modifierChoiceId"
          } ],
          "modifierGroupId" : "modifierGroupId"
        } ],
        "status" : { }
      }
    },
    "OrderLineStatus" : {
      "type" : "string",
      "description" : "Represents the status of a given Orderline.\nUnknown = 0,\nOrdered = 1, // This orderline was not yet commited/confirmed\nCommitted = 2,\nPaid = 3",
      "enum" : [ "unknown", "ordered", "committed", "paid" ],
      "x-enumNames" : [ "Unknown", "Ordered", "Committed", "Paid" ],
      "x-enum-string" : true
    },
    "OrderLineModifier" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "modifierGroupId" : {
          "type" : "string"
        },
        "textInput" : {
          "type" : "string"
        },
        "faxInputID" : {
          "type" : "string",
          "description" : "The ID of the FaxInput image. Can be a number, url, ...\nThe format if this ID is defined by the POS storage behavior.\nTODO: When the FaxInput storage API is defined we may have to update this."
        },
        "choices" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/OrderLineModifierChoice"
          }
        }
      },
      "example" : {
        "textInput" : "textInput",
        "faxInputID" : "faxInputID",
        "id" : "id",
        "choices" : [ {
          "amount" : 1,
          "choicePrice" : 5,
          "modifierChoiceId" : "modifierChoiceId"
        }, {
          "amount" : 1,
          "choicePrice" : 5,
          "modifierChoiceId" : "modifierChoiceId"
        } ],
        "modifierGroupId" : "modifierGroupId"
      }
    },
    "OrderLineModifierChoice" : {
      "type" : "object",
      "properties" : {
        "modifierChoiceId" : {
          "type" : "string"
        },
        "amount" : {
          "type" : "integer",
          "format" : "int32"
        },
        "choicePrice" : {
          "type" : "integer",
          "format" : "int32"
        }
      },
      "example" : {
        "amount" : 1,
        "choicePrice" : 5,
        "modifierChoiceId" : "modifierChoiceId"
      }
    },
    "ServiceArea" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        }
      },
      "example" : {
        "name" : "name",
        "id" : "id"
      }
    },
    "TableResult" : {
      "type" : "object",
      "required" : [ "bookedAmount", "lastActivityTime" ],
      "properties" : {
        "id" : {
          "type" : "string",
          "description" : "ID of the table."
        },
        "name" : {
          "type" : "string",
          "description" : "Name of the table."
        },
        "lastActivityTime" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "Last time there was activity on this table. (Unix Timestamp in seconds = seconds since Jan 01 1970 UTC)"
        },
        "bookedAmount" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "The amount (that finally has to be paid) that is currently booked on this table .\nThis is the sum of all orderlines in all subtables of this table including possible choice prices."
        },
        "subTables" : {
          "type" : "array",
          "description" : "The subtables of this table.",
          "items" : {
            "$ref" : "#/definitions/SubTable"
          }
        },
        "serviceAreaId" : {
          "type" : "string",
          "description" : "The ID of the service area this table belongs to."
        }
      },
      "example" : {
        "bookedAmount" : 6,
        "subTables" : [ {
          "name" : "name",
          "isSelected" : true,
          "id" : "id"
        }, {
          "name" : "name",
          "isSelected" : true,
          "id" : "id"
        } ],
        "name" : "name",
        "id" : "id",
        "lastActivityTime" : 0,
        "serviceAreaId" : "serviceAreaId"
      }
    },
    "SubTable" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string",
          "description" : "The ID of the subtable.\n            "
        },
        "name" : {
          "type" : "string",
          "description" : "The name of the subtable."
        },
        "isSelected" : {
          "type" : "boolean",
          "description" : "If true this subtable will be selected when the table is opened. Can be used to directly show another subtable as the first one int he list to the user."
        }
      },
      "description" : "Information about the subtable",
      "example" : {
        "name" : "name",
        "isSelected" : true,
        "id" : "id"
      }
    },
    "User" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string",
          "description" : "The user / employee identifier.\nWill be used in the auth/login action."
        },
        "name" : {
          "type" : "string",
          "description" : "The employees real name like John Doe.\nThis name will be shown on the statusbar of the clients after login"
        }
      },
      "example" : {
        "name" : "name",
        "id" : "id"
      }
    },
    "LoginUser" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string",
          "description" : "For example when doing user selection via list with PIN the Id is the id of the employee selected from the list of data/employees."
        },
        "password" : {
          "type" : "string",
          "description" : "Optional. Only provided if a real login authentication procedure was executed.\nFor example when doing user selection via list with PIN the PIN is the password."
        }
      },
      "example" : {
        "password" : "password",
        "id" : "id"
      }
    },
    "POSInfo" : {
      "type" : "object",
      "required" : [ "utcTime" ],
      "properties" : {
        "restaurantName" : {
          "type" : "string",
          "description" : "The name of the restaurant we are working with."
        },
        "utcTime" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "The current UTC time stamp (in seconds since epoch time).\nUsed for synchronization between clients and the server."
        },
        "clientName" : {
          "type" : "string",
          "description" : "If provided this name will be shown in the connection / login screen instead of the device name configured in the device (done via SC2).\nIf not provided the original name as provided in the request / ClientInfo is shown."
        }
      },
      "description" : "Provides site specific data on successful initialization.",
      "example" : {
        "restaurantName" : "restaurantName",
        "clientName" : "clientName",
        "utcTime" : 0
      }
    },
    "ClientInfo" : {
      "type" : "object",
      "properties" : {
        "version" : {
          "type" : "string",
          "description" : "The version of the remote client application we are talking to."
        },
        "id" : {
          "type" : "string",
          "description" : "The id of the remote client we are talking to. (should consist of an application name + device serial nummber)"
        },
        "clientName" : {
          "type" : "string",
          "description" : "The configured device name that can be configured via SC2 and is shown in our top status bar in the connect screen."
        },
        "printerPath" : {
          "type" : "string",
          "description" : "Optional. A path to the printer that can be used for send print jobs to this client if it supports them.\nFor Orderman handheld devices this path will be provided if an Orderman belt printer is paired with that device.\nTo send print jobs you can use the \"/printers\" api of the OsServer instance this init request was coming from.\nExample (we assume the OsServer is running on local host and it's httpApi port is configured to 12344:\n    - You receive the path \"/printers/125-49944541\"\n    - You can query details about this printer via \"GET http://localhost:12344/api/v1/printers/125-49944541\"\n    - To send a new print job: \"POST http://localhost:12344/api/v1/printers/125-49944541/jobs\" which will return \n      with a print job id immediately (in this example 38428)\n    - to query the print job status: \"GET http://localhost:12344/api/v1/printers/125-49944541/jobs/38428\""
        }
      },
      "description" : "Holds data about the remote client application / device that want's to communicate with the POS system.",
      "example" : {
        "printerPath" : "printerPath",
        "clientName" : "clientName",
        "id" : "id",
        "version" : "version"
      }
    },
    "GatewayInfo" : {
      "type" : "object",
      "properties" : {
        "httpApiPort" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "The gateways port at which we can query status via http. For OsServer the default configuration in the configuration file is 12344.\nIf omitted the gatway does not support status queries."
        },
        "name" : {
          "type" : "string",
          "description" : "The gatways name. In case of OsServer this name is defined in the servers configuration file."
        },
        "id" : {
          "type" : "string",
          "description" : "The gatways ID. In case of an OsServer this ID is automatically generated on first start or set via the configuration file."
        },
        "gatewaySessionId" : {
          "type" : "string",
          "description" : "The session ID of the gatway. It will change whenever the gateway restarts."
        }
      },
      "example" : {
        "httpApiPort" : 0,
        "name" : "name",
        "id" : "id",
        "gatewaySessionId" : "gatewaySessionId"
      }
    },
    "OrderLineVoidResult" : {
      "type" : "object",
      "required" : [ "quantity", "singlePrice" ],
      "properties" : {
        "orderLineId" : {
          "type" : "string",
          "description" : "The ID of the orderline that a void operation was executed on."
        },
        "singlePrice" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "The single price of the orderline.\nThis will typically be the same as before but it might change in case of volumen discounts."
        },
        "quantity" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "The new quantiy of this orderline."
        }
      },
      "description" : "Provides information about the new status of the orderline after void processing.",
      "example" : {
        "singlePrice" : 0,
        "quantity" : 6,
        "orderLineId" : "orderLineId"
      }
    },
    "OrderLineVoid" : {
      "type" : "object",
      "properties" : {
        "quantity" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "Defines the quantity that is voided from an existing orderline.\nIf the quanity is 0 nothing is changed.\nIf the quantity is &gt;= the quantity of the orderline the whole orderline will be voided."
        },
        "cancellationReasonId" : {
          "type" : "string",
          "description" : "Defines the cancellation reasion that must be provided if a already commited orderline should\nbe voided."
        }
      },
      "example" : {
        "quantity" : 0,
        "cancellationReasonId" : "cancellationReasonId"
      }
    },
    "OrderLineResult" : {
      "type" : "object",
      "required" : [ "singlePrice" ],
      "properties" : {
        "id" : {
          "type" : "string",
          "description" : "The ID of the orderline in question."
        },
        "singlePrice" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "The single price of the order line / article."
        },
        "modifiers" : {
          "type" : "array",
          "description" : "The modifiers of that orderline.",
          "items" : {
            "$ref" : "#/definitions/OrderLineResultModifier"
          }
        }
      },
      "example" : {
        "singlePrice" : 0,
        "id" : "id",
        "modifiers" : [ {
          "id" : "id",
          "choices" : [ {
            "choicePrice" : 6,
            "modifierChoiceId" : "modifierChoiceId"
          }, {
            "choicePrice" : 6,
            "modifierChoiceId" : "modifierChoiceId"
          } ]
        }, {
          "id" : "id",
          "choices" : [ {
            "choicePrice" : 6,
            "modifierChoiceId" : "modifierChoiceId"
          }, {
            "choicePrice" : 6,
            "modifierChoiceId" : "modifierChoiceId"
          } ]
        } ]
      }
    },
    "OrderLineResultModifier" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string",
          "description" : "The ID of that modifier selection that uniquly identifies this entry."
        },
        "choices" : {
          "type" : "array",
          "description" : "The modifer chioces.",
          "items" : {
            "$ref" : "#/definitions/OrderLineResultModifierChoice"
          }
        }
      },
      "example" : {
        "id" : "id",
        "choices" : [ {
          "choicePrice" : 6,
          "modifierChoiceId" : "modifierChoiceId"
        }, {
          "choicePrice" : 6,
          "modifierChoiceId" : "modifierChoiceId"
        } ]
      }
    },
    "OrderLineResultModifierChoice" : {
      "type" : "object",
      "properties" : {
        "modifierChoiceId" : {
          "type" : "string",
          "description" : "The ID of the choices in question."
        },
        "choicePrice" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "If provided the price of that choice."
        }
      },
      "example" : {
        "choicePrice" : 6,
        "modifierChoiceId" : "modifierChoiceId"
      }
    },
    "OrderLineAdd" : {
      "type" : "object",
      "properties" : {
        "quantity" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "The quantity for this order line. When adding a new order line this value must be set."
        },
        "enteredPrice" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "Defines a manual price for this order line.\nNOTE: You must not provide this parameter if you want the price to be calculated by the POS."
        },
        "modifiers" : {
          "type" : "array",
          "description" : "Modifiers to be assigned for this orderline.",
          "items" : {
            "$ref" : "#/definitions/OrderLineModifier2"
          }
        },
        "articleId" : {
          "type" : "string",
          "description" : "The ID of the article ordered with this orderline."
        }
      },
      "example" : {
        "quantity" : 0,
        "articleId" : "articleId",
        "enteredPrice" : 6,
        "modifiers" : [ {
          "textInput" : "textInput",
          "faxInputID" : "faxInputID",
          "choices" : [ {
            "amount" : 1,
            "modifierChoiceId" : "modifierChoiceId"
          }, {
            "amount" : 1,
            "modifierChoiceId" : "modifierChoiceId"
          } ],
          "modifierGroupId" : "modifierGroupId"
        }, {
          "textInput" : "textInput",
          "faxInputID" : "faxInputID",
          "choices" : [ {
            "amount" : 1,
            "modifierChoiceId" : "modifierChoiceId"
          }, {
            "amount" : 1,
            "modifierChoiceId" : "modifierChoiceId"
          } ],
          "modifierGroupId" : "modifierGroupId"
        } ]
      }
    },
    "OrderLineModifier2" : {
      "type" : "object",
      "properties" : {
        "modifierGroupId" : {
          "type" : "string",
          "description" : "The ID of the modifier group this modifiers belong to. This must be the groupd ID the choices belong to."
        },
        "textInput" : {
          "type" : "string",
          "description" : "The enterd text in case the modifier group is of type free text entry."
        },
        "faxInputID" : {
          "type" : "string",
          "description" : "The ID of the FaxInput image in case the modifier group is of type fax. Can be a number, url, ...\nThe format if this ID is defined by the POS storage behavior.\nTODO: When the FaxInput storage API is defined we may have to update this."
        },
        "choices" : {
          "type" : "array",
          "description" : "The selected choices in case modifier group is of type PickOne, PickMultiple, PickNumeric, Pick...",
          "items" : {
            "$ref" : "#/definitions/OrderLineModifierChoice2"
          }
        }
      },
      "example" : {
        "textInput" : "textInput",
        "faxInputID" : "faxInputID",
        "choices" : [ {
          "amount" : 1,
          "modifierChoiceId" : "modifierChoiceId"
        }, {
          "amount" : 1,
          "modifierChoiceId" : "modifierChoiceId"
        } ],
        "modifierGroupId" : "modifierGroupId"
      }
    },
    "OrderLineModifierChoice2" : {
      "type" : "object",
      "properties" : {
        "modifierChoiceId" : {
          "type" : "string",
          "description" : "The ID of the choice that was selected."
        },
        "amount" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "The amount how often the choices was selected. Defaults to 1 if omitted."
        }
      },
      "example" : {
        "amount" : 1,
        "modifierChoiceId" : "modifierChoiceId"
      }
    },
    "OrderLineModify" : {
      "type" : "object",
      "properties" : {
        "quantity" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "The quantity for this order line. When adding a new order line this value must be set."
        },
        "enteredPrice" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "Defines a manual price for this order line.\nNOTE: You must not provide this parameter if you want the price to be calculated by the POS."
        },
        "modifiers" : {
          "type" : "array",
          "description" : "The modifiers for this orderline.",
          "items" : {
            "$ref" : "#/definitions/OrderLineModifier2"
          }
        }
      },
      "example" : {
        "quantity" : 0,
        "enteredPrice" : 6,
        "modifiers" : [ {
          "textInput" : "textInput",
          "faxInputID" : "faxInputID",
          "choices" : [ {
            "amount" : 1,
            "modifierChoiceId" : "modifierChoiceId"
          }, {
            "amount" : 1,
            "modifierChoiceId" : "modifierChoiceId"
          } ],
          "modifierGroupId" : "modifierGroupId"
        }, {
          "textInput" : "textInput",
          "faxInputID" : "faxInputID",
          "choices" : [ {
            "amount" : 1,
            "modifierChoiceId" : "modifierChoiceId"
          }, {
            "amount" : 1,
            "modifierChoiceId" : "modifierChoiceId"
          } ],
          "modifierGroupId" : "modifierGroupId"
        } ]
      }
    },
    "PaySubTables" : {
      "allOf" : [ {
        "$ref" : "#/definitions/PayBase"
      }, {
        "type" : "object",
        "required" : [ "subTableIds" ],
        "properties" : {
          "subTableIds" : {
            "type" : "array",
            "description" : "Array of sub table ids. The sum of the amount of all these subtables together will be paid by \nPayments.\nNOTE: The sub table IDs can only be from the same table. An error will be returned if they are from more then one\ntable.",
            "items" : {
              "type" : "string"
            }
          }
        },
        "description" : "Pay data describing which payments have to be executed for paying full subtables with all their order lines."
      } ]
    },
    "PayBase" : {
      "type" : "object",
      "properties" : {
        "payments" : {
          "type" : "array",
          "description" : "The payments to be executed on the amount sum we get from all the sub tables in SubTableIds.\nSpecial Case: Empty payments / Payments omitted is used to close empty tables.",
          "items" : {
            "$ref" : "#/definitions/Payment"
          }
        },
        "printer" : {
          "type" : "string",
          "description" : "Identifies the printer to send the receipt print job to. \nexample: 'local://1'\ncheck GET /api/v2/data/Printers to get a list of supported print targets"
        }
      },
      "description" : "Base type for executing payments for something and execute print jobs (like for the bill for that payment).",
      "x-abstract" : true
    },
    "Payment" : {
      "type" : "object",
      "required" : [ "amountPaid" ],
      "properties" : {
        "amountPaid" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "The amount that will get paid."
        },
        "paymentMediaId" : {
          "type" : "string",
          "description" : "The payment media type (id) used for this amount. (example: Cash, Credit Card, ...)"
        }
      },
      "description" : "Describes a single payment done. A receipt can be paid with several different payments."
    },
    "PayOrderLines" : {
      "allOf" : [ {
        "$ref" : "#/definitions/PayBase"
      }, {
        "type" : "object",
        "properties" : {
          "paidLines" : {
            "type" : "array",
            "description" : "List of order line payments that represent the orderlines (-parts) that will be paied with this set.",
            "items" : {
              "$ref" : "#/definitions/OrderLineQuanity"
            }
          }
        }
      } ]
    },
    "OrderLineQuanity" : {
      "type" : "object",
      "required" : [ "quantity" ],
      "properties" : {
        "orderLineId" : {
          "type" : "string",
          "description" : "The ID of the orderline to be paid."
        },
        "quantity" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "The quantity of the orderline in question that should be paid.\nIMPORTANT: This can be the full orderline or just a part of it."
        }
      }
    }
  },
  "x-generator" : "NSwag v11.20.1.0 (NJsonSchema v9.11.0.0 (Newtonsoft.Json v12.0.0.0))"
}
